# favicon.ico
location = /favicon.ico {
    include       nginxconfig.io/security.conf;
    root          /usr/share/nginx/html;
    try_files     $uri =404;
    add_header    Cache-Control "public, max-age=604800" always;
    log_not_found off;
}

# . files
location ~ /\.(?!well-known) {
    deny all;
}

# assets, media
location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|webp|mp4|webm|svg)$ {
    include    nginxconfig.io/security.conf;
    root       /usr/share/nginx/html;
    try_files  $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
}

# svg, fonts
location ~* \.(?:ttf|otf|woff2?)$ {
    include    nginxconfig.io/security.conf;
    root       /usr/share/nginx/html;
    try_files  $uri =404;
    add_header Access-Control-Allow-Origin "*";
    add_header Cache-Control "public, max-age=31536000, immutable";
}

# gzip
gzip            on;
gzip_vary       on;
gzip_proxied    any;
gzip_comp_level 6;
gzip_types      text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml image/png;